---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ app.namespace }}

resources:
{% for res in my.resources() %}
- {{ res.dirname }}/{{ res.filename }}
{% endfor %}

patchesStrategicMerge:
{% for pat in my.patches() %}
- patches/{{ pat.filename }}
{% endfor %}

configMapGenerator:
{% for cm in strukt.get("configmaps",{}).keys()  %}
- name: {{ cm }}
  options:
    labels:
      config-map: {{ cm }}
  {% if strukt.configmaps[cm].get("vars",{}) %}
  literals:
    {% for varname in strukt.configmaps[cm].get("vars",{}).keys() %}
     - {{ varname }}={{ my.var(cm, varname) }}
    {% endfor %}
  {% endif %}
  {% if strukt.configmaps[cm].get("files",{}) %}
  files:
    {% for filename in strukt.configmaps[cm].get("files",[]) %}
     - {{ filename }}
    {% endfor %}
  {% endif %}
{% endfor %}

secretGenerator:
{% for cm in strukt.get("secrets",{}).keys()  %}
- name: {{ cm }}
  options:
    labels:
      secret: {{ cm }}
  {% if strukt.secrets[cm].get("vars",{}) %}
  literals:
    {% for varname in strukt.secrets[cm].get("vars",{}).keys() %}
     - {{ varname }}={{ strukt.secrets[cm].vars[varname ] }}
    {% endfor %}
  {% endif %}
  {% if strukt.secrets[cm].get("files",{}) %}
  files:
    {% for filename in strukt.secrets[cm].get("files",[]) %}
     - {{ filename }}
    {% endfor %}
  {% endif %}
{% endfor %}
