apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ app.name }}
spec:
  replicas: {{ env.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ app.name }}
  template:
    metadata:
      name: {{ app.name }}
      labels:
        app: {{ app.name }}
      annotations:
        app.kubernetes.io/name: {{ app.name }}
        app.kubernetes.io/version: "{{ app.version }}"
        app.kubernetes.io/component: webservice
        app.kubernetes.io/part-of: {{ env.project }}
        app.kubernetes.io/managed-by: kustomize
        co.elastic.logs/enabled: "true"
        co.elastic.logs/exclude_lines: DEBUG
    spec:
      #restartPolicy: Never
      containers:
      - name: app
        image: {{ app.image_repo }}/{{ app.name }}.app:{{ app.version }}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ app.name }}-secrets
        - configMapRef:
            name: {{ app.name }}-vars
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 512M
          requests:
            cpu: 200m
            memory: 512M
