---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ my.name }}
  {% if "nginx_snippets" in strukt %}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
    {% for line in strukt.nginx_snippets %}
      {{line}}
    {% endfor %}
  {% else %}
  annotations: {}
  {% endif %}
    #app.kubernetes.io/name: {{ app.appname }}
spec:
  rules:
    - host: {{ my.field.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ strukt.path or "/" }}
            backend:
              service:
                name: {{ my.field.service }}
                port:
                  number: {{ my.field.containerPort }}
